services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: testpassword
      MARIADB_DATABASE: testDB
    networks:
      - internal
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "3006:3000"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: testpassword
      DB_NAME: testDB
    depends_on:
      - db
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_data:
