services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: testpassword
    networks:
      - internal
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: testpassword
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - db_data:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  db_data:
